# Use the official Node.js image as the base image
FROM node:lts-bullseye-slim

# Set the working directory to /app
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the container
COPY package.json ./
COPY bun.lockb ./

# Install pnpm
RUN npm install -g bun

# Install the dependencies
RUN bun install

# Copy the rest of the application code to the container
COPY . .

# Set the environment variable to development
ENV NODE_ENV=development

# Start the application
CMD ["bun", "run", "dev"]