version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
